name: flick-articles-backend-prod
services:
  mongo:
    restart: unless-stopped
    image: mongo:8.0.3
    volumes:
      - mongo_data:/data/db
    networks:
      - flick-backend
  redis:
    restart: unless-stopped
    image: redis:7.4.1
    volumes:
      - redis_data:/data
    networks:
      - flick-backend
    depends_on:
      - mongo
  api:
    build:
      context: ./
      target: production
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - flick-backend
    depends_on:
      - redis
      - mongo

volumes:
  redis_data:
  mongo_data:
networks:
  flick-backend:
    driver: bridge
