name: flick-articles-backend-dev

services:
  mongo:
    restart: unless-stopped
    image: mongo:8.0.3
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - flick-backend
  redis:
    restart: unless-stopped
    image: redis:7.4.1
    volumes:
      - redis_data:/data
    networks:
      - flick-backend
    depends_on:
      - mongo
  api:
    build:
      context: ./
      target: development
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - flick-backend
    depends_on:
      - redis
      - mongo

volumes:
  redis_data:
  mongo_data:
networks:
  flick-backend:
    driver: bridge
