import { DarkModeProvider } from "@/Contexts/DarkModeContext";
import "@/../node_modules/bootstrap/dist/css/bootstrap.css";
/* import "@/../node_modules/bootstrap/dist/js/bootstrap.bundle"; */
import "@/../node_modules/bootstrap-icons/font/bootstrap-icons.css";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <DarkModeProvider>
        <body>{children}</body>
      </DarkModeProvider>
    </html>
  );
}
